# Environmental/Networking details
SYSTEM_PROTOCOL: http
CONNECTION_TIMEOUT: 60
SYSTEM_HOST: mars.theblueground.net
ENVIRONMENT: BlueGroundMars

# Static data to be used on our cases
VALID_EMAIL: ben@2041.uk
VALID_PASSWORD: idietoosoon
VALID_UNIT_ID: 5beb3e86ef21650028b13ed0
WRONG_UNIT_ID: wrongUnitId
WRONG_EMAIL: wrong@wrong.net
WRONG_PASSWORD: wrongPassword
INVALID_EMAIL: invalid@mail.error
INVALID_TOKEN: invalidToken
EXPIRED_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NTEzNTY3NTcsImlhdCI6MTU1MTI3MDM1Nywic3ViIjoiNWJlYjNlODZlZjIxNjUwMDI4YjEzZTlmIn0.47TpxM9zDSVP9TMI5FxDN99ZiaxS9bKqLRAYyRvTUDo
UNAVAILABLE_YEAR: '2040'
MAX_UNITS_PER_PAGE: '5000'
MAX_LOG_SIZE: 5000

# REQUEST STATUS CODES
SUCCESS_CODE: '200'
BAD_REQUEST_CODE: '400'
UNAUTHORIZED_USER_CODE: '401'
NOT_FOUND_CODE: '404'
CONFLICT_CODE: '409'
